language: node_js
node_js:
  - 9.8
env:
  global:
    - REACT_APP_BACKEND_URL=https://tfgbackend0.herokuapp.com/
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
stages:
  - name: deploy
    if: branch = master
deploy:
  provider: heroku
  api_key:
    secure: LJTzIZbGIo8RQzDp5rfctd6wJ930npUlh574tq7V7Exfx7ubGIk1TGaEJ8/x8BmvfCWCXvtP439Stx9VZf7FbP5l5PMedtT8y95OhrYiH/YEdqmC77yj/6AUupsXxlxVp2mqTgGB0KLWf2AgXdPpyOlf0GjtL5QY4e4kCGlQIw3iB5qw7aODJh8Wt4OfdV2c4ZtjhyqKNs0w01JEVyf8cxxKCJuvPaNRTKHoqHiwo3DbM6w7aIqY+vZYSdTPzqnsqnPFNZtenJJtLnGDyxLIKkGjdy4MUDqg7fpgWMO78vyDAzplOOIG9N4mNl1BWGhK3jYCZKeMp9eFXU+8Eg4i0Wn9pbkgXjE9dnMuXOwLUNX9XHWImMTRb0PAjAJxuMlvDSC0ze3hGASHsOY8X0ezQ+5+tZM301a08skV5Ef+IWdYQL+FTJACTuDuJy5uKduZh/M7ONfm1ZU/jTIKFnYzZc8eIxPjWjLSR5LuCoxvcVyqJ1rAu5lgbj9x0I9YLiES+9g69jfXrrS1DAiq9Hr8wqKViJfrTSZ+SeoFdA9Q/n+MdLH0BRQ3Tk/xVOwdVswDmVmf/WPORTHV59revkNzqSoHJdLeM0m9UJSgIEzNcGUoy+wx3WW2dztlSJAJWOEElMBby5JViarR0GGLqKCf35vQTRuEDimyoFpK5Y/aHW4=
  app: tfgfrontend0
  run:
    - npm start