language: node_js
node_js:
- 9.8
env:
  global:
  - REACT_APP_BACKEND_URL=https://tfgbackend0.herokuapp.com/
cache:
  directories:
  - node_modules
script:
- npm run build
stages:
- name: deploy
  if: branch = master
deploy:
  provider: heroku
  api_key:
    secure: j1CfQb5DisC0V9sxO6O3rCyYHj2q7LBNXEpA32bi8HlTNKgJgOVBCzOiQgfNj3mqX/MG1Rq9VIe2QDtCDslhU0I0K6FTBaOhE8pK6va0ioJeLF/1G9BXmgpKDXEvwuiVbouV0Tr/wyrixWsmxRkF0f3ALiN6CUVgQ/82Dic91QJpSFBEpKzSGWbRQw/2tfZD+a69WZ13xDsamOOG+xxQVEgxPdGwi+35sruTrkd48zrH7f4qzfIeM5ifRwdpIxNfCzjoz5KOfOdoeBcEGMMyb3/xu2WjE4PeusiQqvq0p9rYpoCZBk5yXswqtg7yfR/WYbETEuyRAMvblEsSL6k4sAit8I6MUrrxPNVwRy5bq5VQnHFXk6HzloKw3lVD8ZUjvXZNWBdkBEypDgXOjBKQDJCYTnER5TTmvxRbL+F7WdhHN7xMh5RSmmYymYLVPcecN8kBoIT8tMWee6PmSv6H2DotofCdW9G2/pxGIrY6ZS5Fy3VtjrK7MebB+bF/SfaWUgPnGTLy9U+GKYdAMgZ6Ph+AOmzDdzW3LHrMwnQw2MX99WkQ+8vS++AYYb2MiUaD+zZcyYQvfQZ/KMA4NPP8jNUVKnHmALkm7BycJYDVCqeeBbpHzOXY0d8YtfldBtlOSTGbb5XI/Q0arptX3Sy9zujUZCJK81uq0KXrTnGXqaU=
  app: tfgfrontend0
